name: Build snapshots

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'
      - 'prod'

env:
  CARGO_TERM_COLOR: always
  SCCACHE_CACHE_SIZE: 2G
  RUSTC_WRAPPER: sccache
  CARGO_INCREMENTAL: "0"

jobs:
  build-linux:
    name: Linux (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools mold

      - name: Cache Cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --profile snapshot --target ${{ matrix.target }}
        env:
          RUSTFLAGS: -C linker=clang -C link-arg=-fuse-ld=mold

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target}}
          path: target/${{ matrix.target }}/snapshot/[^.]*
          if-no-files-found: error
          retention-days: 7

      - name: Upload debug symbols artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}@debug
          path: |
            target/${{ matrix.target }}/snapshot/*.dSYM
            target/${{ matrix.target }}/snapshot/*.debug
          if-no-files-found: error
          retention-days: 7


  build-macos:
    name: macOS (${{ matrix.target }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: x86_64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --profile snapshot --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target}}
          path: target/${{ matrix.target }}/snapshot/[^.]*
          if-no-files-found: error
          retention-days: 7

      - name: Upload debug symbols artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}@debug
          path: target/${{ matrix.target }}/snapshot/*.dSYM
          if-no-files-found: error
          retention-days: 7


  build-windows:
    name: Windows (${{ matrix.target }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
          - target: aarch64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --profile snapshot --target ${{ matrix.target }}
        env:
          RUSTFLAGS: -C linker=rust-lld.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target}}
          path: target/${{ matrix.target }}/snapshot/*.exe
          if-no-files-found: error
          retention-days: 7

      - name: Upload debug symbols artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}@debug
          path: target/${{ matrix.target }}/snapshot/*.pdb
          if-no-files-found: error
          retention-days: 7

